### ISSUE TITLE
Split temboard-agent in its own project

### ISSUE THREAD

**Issue by bersace** [dalibo/temboard#108]
### Todo

- [x] Create project https://github.com/dalibo/temboard-agent
- [x] Push temboard-agent code
- [x] Clean temboard #104 
- [x] update docker https://github.com/dalibo/docker/pull/11
- [x] Update both README.md
