### ISSUE TITLE
New plugin : slow queries tracking

### ISSUE THREAD

**Issue by julmon** [dalibo/temboard#632]
# Summary

Slow queries tracking in temboard will be based on a dedicated PostgreSQL extension : `pg_track_slow_queries`.  Details about how this extension works here: https://github.com/julmon/pg_track_slow_queries/blob/master/README.md
This feature will be implemented as a new plugin.
The list of tracked slow queries will be fetched periodically by UI workers calling agent's API. This list is then stored into the repository, into partitioned tables. Due to the potential huge amount of data, we want to apply a short retention policy, maybe 2 or 3 months.

# TODO

## Dev. env.

- [ ] Include `pg_track_slow_queries` extension in dev. environment.

## Repository

- [ ] Data model design using table partitioning
- [ ] PostgreSQL upgrade to 11 (docker)

## temboard-agent

- [ ] API to update `pg_track_slow_queries` settings
- [ ] API to get the list of tracked statements
- [ ] API to execute a query using EXPLAIN ANALYZE, plan format could be json or text

### workers

- [ ] New worker in charge of scheduling the real work (pulling) for each instances we have
- [ ] New worker in charge of pulling queries history and purging its local history from the agent
- [ ] New worker in charge of the retention policy application

### configuration

- [ ] Retention policy and pulling frequency

### UI

- [ ] Table/list of the tracked queries according to a defined time interval : without exec. plan and with truncated query text to N chars.
- [ ] Query details : query full text + execution plan
- [ ] Graphical rendering of execution plans
- [ ] `pg_track_slow_queries` setup page
- [ ] Capability to re-execute a  query using EXPLAIN ANALYZE

**Comment by daamien** [comment]
closed internally
